#+TITLE: Welcome to Raki Finance

* Table Of Contents :toc:
- [[#about-raki-finance][About Raki Finance]]
  - [[#welcome-to-the-future-of-defi][Welcome to the Future of DeFi]]
  - [[#borrow-and-lend-cross-chain-seamlessly][Borrow and Lend Cross Chain, Seamlessly]]

* About Raki Finance
** Welcome to the Future of DeFi

Capital in DeFi is extremely fragmented across chains, evidenced by the dozens of different money markets, all with their own liquidity.

Lenders decide on a chain, and the assets they withdraw must exist on that same chain.

Suppose a DeFi user wants to deposit wBTC on Arbitrum and withdraw ETH on mainnet. In that case, they can only do so by navigating through a series of cumbersome transactions across multiple user endpoints.

This liquidity dispersion creates a suboptimal borrowing and lending experience.

** Borrow and Lend Cross Chain, Seamlessly

Radiant aims to be the first omnichain money market where users can deposit any major asset on any major chain and borrow various supported assets across multiple chains.

The Radiant DAO's primary goal is to consolidate the ~$22 billion of fragmented liquidity dispersed across the top ten alternative layers (source: DefiLlama).

Lenders who provide liquidity to Radiant are interacting and providing utility to the platform. In addition, lenders can capture the added value from the communities’ engagement through the native token $RDNT.

Borrowers can withdraw against collateralized assets to obtain liquidity (working capital) without selling their assets and closing their positions.
